name: avito
volumes:
  pgdata: {}

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-${POSTGRES_USER}}
    expose:
      - ${POSTGRES_PORT:-5432}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT:-5432} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql
    command: ["--port=${POSTGRES_PORT:-5432}"]
    restart: always

  migrate:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    container_name: goose
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DBSTRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-${POSTGRES_USER}}?sslmode=disable
      GOOSE_DRIVER: postgres
    volumes:
      - ./migrations:/migrations:ro
    command: ["up"]
    restart: no

  api:
    build: .
    container_name: api
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
    restart: unless-stopped
